### ISSUE TITLE
Be able to change iRacing's camera by clicking a driver on the timing page

### ISSUE THREAD

**Issue by sonofmaw** [sonofmaw/iTelemetry#7]

**Comment by PascalHigelin** [comment]
At the moment only pit commands are interpreted by the server app
Camera commands need to be added

**Comment by PascalHigelin** [comment]
In a typical scenario the spotter is connected to the driver's computer to be able see tyre and fuel data. No point in trying to change camera in this situation.

This feature could be useful only if connected locally during a replay.

**Comment by PascalHigelin** [comment]
Camera commands have been added on server side.
I think I will change camera on click only if server is localhost.

**Comment by PascalHigelin** [comment]
Changes have been commited.
Requires server app version 1.4.3.0.

**Comment by sonofmaw** [comment]
See #8
