### ISSUE TITLE
Add an indicator on the timing page showing which driver the camera is watching, if any

### ISSUE THREAD

**Issue by sonofmaw** [sonofmaw/iTelemetry#8]

**Comment by PascalHigelin** [comment]
The reference driver (driver in green) could be used.
Reference driver should then reflect camera driver.

**Comment by sonofmaw** [comment]
I think it would be better to keep the reference driver independent of who the camera is watching (even if the changing the reference driver changes the camera - you can still change the camera in-game) I often watch drivers just behind the driver I'm spotting for. A little icon would be enough.

**Comment by PascalHigelin** [comment]
I've added a camera icon in front of the driver holding the camera.
Selected driver and camera driver are synched if host is localhost only

**Comment by sonofmaw** [comment]
I'm changing this a bit - two modes:

1. Camera is synced with selected driver (default). Camera glyph is not shown, iRacing camera follow selected driver and vice versa.
2. New column is added that allow the camera to be focused a driver, indepentently of the selected driver. This column shows the camera glyph, indicating where the iRacing camera is focused.

**Comment by PascalHigelin** [comment]
I'm not sure I understand exactly what you want to do.

When you are spotting for a driver your client webapp must be connected to the server app on the driver side (eventually through the central server) to be able to read tyre and fuel data. In this situation the web app can't change the camera on the spotter side because it is not connected to the local server.

This is why I allowed camera change only if host is localhost

**Comment by sonofmaw** [comment]
Yes, I understand that spotting a driver that is broadcasting data means that it makes no sense to want to change "their" camera. However I use this app quite a bit to spectate and spot races locally (localhost) and being able to switch camera on my local client without having to muck about with iRacing - and be able to see who I'm looking at on the timing screen - is very useful. I'd even be tempted to switch off everything but the timing pages when on localhost.

**Comment by PascalHigelin** [comment]
Glad to hear you use this app quite a bit  :)

We have 2 situations. We can do the following:

* When connected to a remote server we can keep it as it is: no camera change on click and icon in front of driver

* When connected to localhost: click on a driver makes him the selected driver. Shift-click or double-click on a driver moves the camera to the driver

**Comment by sonofmaw** [comment]
So the way I've implemented it is:

- Remote server: All camera features hidden  - no camara change on click and no icons or options
- Localhost: Option added to select one of three modes:
a) Synced with selected driver (as it is now) (default mode)
b) Independently selected: A new column on the timing page shows where the camera is targeted and clicks on this column changes the camera target.
c) Disable camera control: Removes all camera control, as if connected to a remote server.

Remotely connected spotters won't see any difference. Anyone who spectates or spots locally will default to the fully synced mode, but can change to either switch it off or allow full, independent control of the camera.

**Comment by sonofmaw** [comment]
Bit more testing tonight and I'll push it up.

**Comment by sonofmaw** [comment]
Ah, no I wasn't asking you to do it. I was just described what I _had_ done.

**Comment by PascalHigelin** [comment]
Settings.html hasn't been merged correctly

**Comment by PascalHigelin** [comment]
Sorry my fault page was cached :(

**Comment by PascalHigelin** [comment]
I don't get the 3rd mode. It's the same as the second mode but without the camera icon or am I missing something?
If this is the case I don't the benefit of this mode.

**Comment by sonofmaw** [comment]
3rd mode is "off". Camera isn't controlled or synced with/by the web app.
